# Generated by Django 5.1.7 on 2025-03-22 15:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='first_name',
            field=models.CharField(default='DefaultFirstName', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='last_name',
            field=models.CharField(default='DefaultLastName', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
