# Generated by Django 5.1.7 on 2025-03-23 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
