# Generated by Django 5.1.7 on 2025-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_actionlog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
