# Generated by Django 5.1.7 on 2025-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_actionlog_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='user_id_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
