# Generated by Django 5.1.7 on 2025-03-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_actionlog_user_id_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='user_id_uuid',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
