# Generated by Django 5.1.7 on 2025-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_actionlog_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user_email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
    ]