# Generated by Django 5.1.7 on 2025-03-23 19:12

import uuid
from django.db import migrations, models

def convert_user_id_to_uuid(apps, schema_editor):
    schema_editor.execute("""
        ALTER TABLE main_actionlog
        ALTER COLUMN user_id TYPE uuid
        USING (uuid_generate_v4());
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_timestamp_actionlog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
